#.travis.yml

language: node_js
node_js:
  - "8.12.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase use dev
  - firebase deploy --token $FIREBASE_TOKEN
  - ng build -c prod-one
  - firebase use prod-one
  - firebase deploy --token $FIREBASE_TOKEN
  - ng build -c prod-two
  - firebase use prod-two
  - firebase deploy --token $FIREBASE_TOKEN
  - ng build -c prod-three
  - firebase use prod-three
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
