#.travis.yml

language: node_js
node_js: "8.12.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script: ng build --prod

after_success: bash scripts/deploy.sh environments.txt $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
